### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by AJFNC** [LibreClass/libreclass#2]
Na segunda etapa de instalação a linha de comando para instalar o PHP está com uma versão superada (PHP versão 5). A versão atual é a 7.
Sugestão: colocar uma linha de comando que possa servir para qualquer versão atual.

Instale o php5, mysql, composer, etc:
$ sudo apt-get install apache2 php5 php5-mcrypt php5-curl php5-imagick php5-mysql
$ sudo apt-get install mysql-server

**Comment by caioladislau** [comment]
Muito obrigado pela contribuição! Assim que atualizar o README.md com as versões atualizadas eu informarei através desta issue.

**Comment by AJFNC** [comment]
Ok Caio.

Abraço,
Alexandre

Em 15 de jul de 2017 9:46 AM, Caio Ladislau <notifications@github.com> escreveu:

Muito obrigado pela contribuição! Assim que atualizar o README.md com as versões atualizadas eu informarei através desta issue.

**Comment by caioladislau** [comment]
O arquivo README.md foi atualizado e foram incluídas algumas melhorias que tornam a instalação menos complicada.
